### ISSUE TITLE
Using git lfs for storage?

### ISSUE THREAD

**Issue by pratapvardhan** [datameet/pmgsy-geosadak#2]
Should we move to git lfs or split >100mb files into chucks? What's the limit on repo size? cc @thejeshgn @planemad

**Comment by thejeshgn** [comment]
> If you attempt to add or update a file that is larger than 50 MB . GitHub blocks pushes that exceed 100 MB 

> We recommend repositories remain small, ideally less than 1 GB, and less than 5 GB is strongly recommended.

**Comment by pratapvardhan** [comment]
Karnataka roads file is 114mb, what would you suggest? That's the only file pending.

**Comment by thejeshgn** [comment]
What's the current size of the whole repo?

> Every account using Git Large File Storage receives 1 GB of free storage and 1 GB a month of free bandwidth.

**Comment by pratapvardhan** [comment]
Added split files of Karnataka. Dump is complete. Repo size is 2.6GB..
